[package]
name = "aoc_01"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "bench"
harness = false

[dependencies]
anyhow = "^1.0.93"
code-timing-macros = { version = "^0.0.5", features = ["release"] }
itertools = "^0.13.0"

[dev-dependencies]
criterion = "^0.5.1"
