[package]
name = "aoc_01"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "bench"
harness = false

[dependencies]
timing_macro = { path = "../timing_macro" }
itertools = "^0.13.0"

[dev-dependencies]
criterion = "^0.5.1"
